version: "3.7"

services:
  database:
    image: postgres
    container_name: db_app
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_app
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: node_app
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app

volumes:
  pgdata: 
    driver: local
